### ISSUE TITLE
dealing with a lot of data

### ISSUE THREAD

**Issue by BrannonKing** [bradwestness/EPPlusEnumerable#1]
I would like to transfer some large database tables to XLSX. I don't want to have to hold them all in RAM. It would be nice if your tool supported `IQueryable<>` as the input and a target file stream passed via input as well. That byte array is too large to comfortably store in RAM.

**Comment by bradwestness** [comment]
That's a great idea! I'll have to look into that, I'm not sure if EPPlus supports that kind of thing. I know the current implementation I have for the links probably wouldn't work since it enumerates through the collection.
________________________________

**Comment by bradwestness** [comment]
Going to go ahead and close this since it's out of scope for this project. You're probably better off just setting up a database connection directly within Excel if you need to do this kind of large-dataset exporting. The point of this project is to provide a convenient way to create Spreadsheets using the open-source EPPlus library which doesn't support streaming results directly to disk.
