### ISSUE TITLE
Seems to depend on specific version of EPPlus (v4.0.4)

### ISSUE THREAD

**Issue by andrewmurray** [bradwestness/EPPlusEnumerable#16]
I have the following build error:

`16:35:43   d:\Program Files (x86)\Jenkins\jobs\myproject\workspace\source\packages\EPPlusEnumerable.1.4.0.1\lib\net40\EPPlusEnumerable.dll : error CS1705: Assembly 'EPPlusEnumerable, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null' uses 'EPPlus, Version=4.0.4.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' which has a higher version than referenced assembly 'EPPlus, Version=4.0.1.1, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' [D:\Program Files (x86)\Jenkins\jobs\Customer Experience DEV\workspace\source\CustomerExperience.WebUI\CustomerExperience.WebUI.csproj]`

That's after installing only EPPlusEnumerable and allowing NuGet to pull down the appropriate EPPlus version (which it did - v4.0.1.1).

If I then, update the EPPlus version to v4.0.4 the build works no problem and FxCop is happy.

If I then update EPPlus to v4.1.0 (latest of as of writing this), it builds fine but FxCop fails:

`error : CA0058 : The referenced assembly 'EPPlus, Version=4.0.4.0, Culture=neutral, PublicKeyToken=ea159fdaa78159a1' could not be found. This assembly is required for analysis and was referenced by: D:\Program Files (x86)\Jenkins\jobs\Customer Experience DEV\workspace\source\CustomerExperience.WebUI\bin\ArnoldClark.CustomerExperience.WebUI.dll.`

I can run with EPPlus v4.0.4 no problem but package info says that EPPlus >= (greater than or equal to) 4.0 is required.

Seems like there is a hard dependency on v4.0.4 specifically... can the dependency on the specific version be loosened?

**Comment by andrewmurray** [comment]
Does the nuspec specify a specific version, like: http://stackoverflow.com/questions/7772346/how-to-specify-specific-dependency-version-in-nuspec

**Comment by bradwestness** [comment]
In the nuspec the dependency is simply listed as >= EPPlus 4.0, like so:
`        <dependencies>
            <dependency id="EPPlus" version="[4.0, ]" />
        </dependencies>`
the actual project currently has a reference to the EPPlus 4.0.4 NuGet package, so that might be an issue. You could potentially use a binding redirect to use a different version in your app.config, like so:
`
<dependentAssembly>
  <assemblyIdentity name="EPPlus" publicKeyToken="ea159fdaa78159a1" culture="en-us" />
  <bindingRedirect oldVersion="4.0.0-4.1.0" newVersion="4.1.0" />
</dependentAssembly>
`
